"""
email_analyzer.py - Phishing email detection
Combines ML (TF-IDF + Logistic Regression) with rule-based signals.
Covers: credential harvesting, prize scams, advance fee fraud (419),
        hidden hyperlinks, and suspicious anchor text.
Explanations are generated by the LLM explainer when available.
"""

import re
import os
import sys
import joblib

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from src.translations import detect_language, get_explanation, get_risk_label, translate_flag

EMAIL_MODEL_PATH = os.path.join(os.path.dirname(__file__), "..", "models", "email_model.pkl")
_email_model = None


def _load_email_model():
    global _email_model
    if _email_model is None:
        _email_model = joblib.load(EMAIL_MODEL_PATH) if os.path.exists(EMAIL_MODEL_PATH) else "fallback"
    return _email_model


URGENCY = [
    r"act\s+now", r"urgent", r"immediate", r"within\s+\d+\s+hours?",
    r"account.{0,20}(suspend|block|clos|terminat)", r"last\s+chance",
    r"expires?\s+(today|soon)", r"action\s+required", r"verify\s+now",
    r"failure\s+to\s+(act|respond|verify)", r"final\s+warning",
]

CRED_REQ = [
    r"(enter|provide|confirm|update|verify).{0,20}(password|pin|credentials?)",
    r"(enter|provide|confirm|update|verify).{0,20}(bank|credit\s+card|debit)",
    r"social\s+security", r"date\s+of\s+birth", r"mother.?s\s+maiden",
    r"click\s+here\s+to\s+(login|sign\s+in|verify)",
]

PRIZE = [
    r"you\s+(have\s+)?(won|been\s+selected|are\s+a\s+winner)",
    r"congratulations?[!,.]", r"free\s+(gift|prize|iphone|money|voucher)",
    r"claim\s+your\s+(prize|reward)", r"lottery", r"lucky\s+winner",
]

MONEY_TRANSFER = [
    r"wire\s+transfer", r"western\s+union", r"moneygram",
    r"gift\s+card", r"bitcoin|crypto", r"advance\s+fee",
]

SUSPICIOUS_SENDER = [
    r"@\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}",
    r"support@.*\.(ru|tk|xyz|club|info)$",
]

# 419 / advance fee fraud - deliberately polite, bypasses urgency-based filters
ADVANCE_FEE = [
    r"dear\s+(beloved|friend|partner|sir|madam|trusted)",
    r"this\s+message\s+will\s+come\s+to\s+you\s+as\s+(a\s+)?surpri",
    r"permit\s+me\s+(of\s+my\s+desire|to\s+introduce)",
    r"go\s+into\s+business\s+relationship",
    r"(transfer|move|remit).{0,30}(fund|sum|money|million|billion)",
    r"(sum|amount)\s+of\s+(usd|eur|gbp|\$|€)[\s\d,\.]+m?(illion)?",
    r"(late|deceased|dead).{0,20}(father|mother|husband|wife|uncle|president|king)",
    r"(civil\s+war|coup|conflict|unrest|assassination|murder).{0,60}(fund|money|sum|deposit)",
    r"(deposited?|kept|stored).{0,30}(bank|security|safe\s*keeping)",
    r"transfer\s+the\s+fund",
    r"into\s+your\s+(bank\s+)?account",
    r"(reliable|trustworthy|honest)\s+(person|individual|partner)",
    r"(offer|give|pay)\s+you\s+\d+\s*(%|percent)",
    r"\d+\s*%\s+of\s+the\s+(total\s+)?(sum|fund|amount|money)",
    r"\b(benin|cotonou|lagos|abuja|ivory\s+coast|dakar|accra|cameroon)\b.{0,80}(fund|bank|money|transfer)",
    r"\b(libya|syria|iraq|afghanistan|nigeria).{0,80}(fund|war|conflict|government)",
    r"remain\s+(blessed|in\s+peace|yours\s+faithfully)",
    r"reply\s+to\s+(my\s+)?(alternative|private|personal)\s+email",
]

SUSPICIOUS_ANCHOR_TEXT = [
    r"(access|view|open|download|get)\s+(the\s+)?(document|file|attachment|invoice|report|form|contract|agreement|statement)",
    r"(click|tap)\s+here\s+to\s+(access|view|open|download|verify|confirm|update|complete)",
    r"(review|sign|complete|approve)\s+(the\s+)?(document|form|contract|agreement|request)",
    r"(verify|confirm|update)\s+(your\s+)?(account|identity|information|details|email|address)",
    r"(open|view|read)\s+(your\s+)?(secure\s+)?(message|notification|alert)",
    r"(download|get)\s+(your\s+)?(invoice|receipt|statement|report|file)",
    r"(access|view)\s+(the\s+)?(shared\s+)?(file|folder|document|spreadsheet|presentation)",
    r"login\s+to\s+(view|access|confirm)",
    r"(salary|payment|refund|transfer)\s+(documents?|details?|information)",
]

URL_RE = re.compile(r'https?://[^\s<>"\')\]]+|www\.[^\s<>"\')\]]+')

HTML_ANCHOR_RE = re.compile(
    r'<a\s[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>',
    re.IGNORECASE | re.DOTALL
)


def _analyze_html_links(text: str) -> list:
    findings = []
    matches = HTML_ANCHOR_RE.findall(text)
    if not matches:
        return findings

    from src.predict import predict as predict_url

    for href, anchor_text in matches:
        anchor_clean = re.sub(r'<[^>]+>', '', anchor_text).strip()
        href = href.strip()

        if not href or href.startswith('mailto:') or href.startswith('#'):
            continue

        anchor_looks_like_url = bool(re.match(r'https?://', anchor_clean))
        if anchor_looks_like_url:
            anchor_domain = re.sub(r'^https?://', '', anchor_clean).split('/')[0]
            href_domain   = re.sub(r'^https?://', '', href).split('/')[0]
            if anchor_domain.lower() != href_domain.lower():
                findings.append({
                    "category": "Hidden URL Mismatch",
                    "detail": (
                        f"Visible text shows '{anchor_clean[:60]}' "
                        f"but the link actually goes to '{href[:80]}'. "
                        "This is a classic phishing technique."
                    ),
                    "score": 4,
                })
                continue

        url_result = predict_url(href)
        if url_result["risk_level"] in ("high", "medium"):
            findings.append({
                "category": "Suspicious Link Behind Text",
                "detail": (
                    f"The text '{anchor_clean[:50]}' hides a {url_result['risk_level']}-risk URL: "
                    f"'{href[:80]}' ({url_result['probability']}% phishing probability)."
                ),
                "score": 3 if url_result["risk_level"] == "medium" else 4,
            })

    return findings


def _check_suspicious_anchor_text(text: str) -> list:
    findings = []
    t = text.lower()
    hits = [re.search(pat, t).group(0) for pat in SUSPICIOUS_ANCHOR_TEXT if re.search(pat, t)]

    if hits:
        visible_urls = URL_RE.findall(text)
        if not visible_urls:
            findings.append({
                "category": "Possible Hidden Hyperlink",
                "detail": (
                    f"Contains '{hits[0]}' - a phrase commonly used as clickable link text in phishing emails. "
                    "No visible URL shown, so the real destination is hidden. "
                    "If you received this as an HTML email, hover over any links before clicking."
                ),
                "score": 3,
            })
        else:
            findings.append({
                "category": "Suspicious Link Text",
                "detail": (
                    f"'{hits[0]}' is commonly used to trick users into clicking hidden or disguised links. "
                    "Check all links carefully."
                ),
                "score": 1,
            })

    return findings


def _matches(text, patterns):
    t = text.lower()
    return sum(1 for p in patterns if re.search(p, t))


def _rule_score(text, sender=""):
    flags = []
    score = 0
    is_html = bool(re.search(r'<html|<body|<a\s+href', text, re.IGNORECASE))

    if is_html:
        html_findings = _analyze_html_links(text)
        for f in html_findings:
            score += f.pop("score", 2)
            flags.append(f)

    anchor_findings = _check_suspicious_anchor_text(text)
    for f in anchor_findings:
        score += f.pop("score", 2)
        flags.append(f)

    u = _matches(text, URGENCY)
    if u:
        score += min(u, 2)
        flags.append({
            "category": "Urgency / Pressure",
            "detail": f"Found {u} urgency phrase(s). Phishing emails pressure you to act fast."
        })

    c = _matches(text, CRED_REQ)
    if c:
        score += 2
        flags.append({
            "category": "Requests Personal Information",
            "detail": "Asks for passwords, PINs, or banking details. Legitimate organisations never do this by email."
        })

    p = _matches(text, PRIZE)
    if p:
        score += 2
        flags.append({
            "category": "Prize / Lottery Claim",
            "detail": "Claims you've won something. Classic social engineering tactic."
        })

    m = _matches(text, MONEY_TRANSFER)
    if m:
        score += 3
        flags.append({
            "category": "Money Transfer Request",
            "detail": "Mentions wire transfers, gift cards, or cryptocurrency. Major fraud warning signs."
        })

    af = _matches(text, ADVANCE_FEE)
    if af >= 2:
        score += min(af, 5)
        flags.append({
            "category": "Advance Fee Fraud (419 Scam)",
            "detail": (
                f"Found {af} indicators of advance fee fraud. "
                "These emails invent a story about a large sum of money and promise a cut. "
                "In reality, victims are asked to pay fees upfront and receive nothing."
            )
        })

    large_sum = re.search(r'(usd|eur|\$|€)\s*[\d,]+[\s,]*(000|million|m\b)', text.lower())
    if large_sum and af >= 1:
        score += 2
        flags.append({
            "category": "Large Sum of Money Mentioned",
            "detail": "Unexpected wealth offers are almost always scams."
        })

    alt_email = re.search(r'reply\s+to.{0,60}@', text.lower())
    if alt_email:
        score += 2
        flags.append({
            "category": "Reply-to Different Address",
            "detail": "Asking you to reply to a different address hides the real sender."
        })

    urls = URL_RE.findall(text)
    if urls and not is_html:
        flags.append({
            "category": f"Contains {len(urls)} URL(s)",
            "detail": f"{', '.join(urls[:3])}{'...' if len(urls) > 3 else ''}"
        })

    if sender:
        from src.typosquatting import check_typosquatting
        sd = sender.lower().split("@")[-1] if "@" in sender else ""
        for pat in SUSPICIOUS_SENDER:
            if re.search(pat, sender.lower()):
                score += 2
                flags.append({
                    "category": "Suspicious Sender Address",
                    "detail": f"Sender '{sender}' has characteristics of phishing emails."
                })
                break
        if sd:
            typo = check_typosquatting("http://" + sd)
            if typo["is_typosquat"]:
                score += 2
                flags.append({
                    "category": "Sender Domain Impersonation",
                    "detail": f"'{sd}' looks like it's impersonating '{typo['matched_brand']}'. {typo['explanation']}"
                })

    if text.count("!") >= 3:
        score += 1
        flags.append({
            "category": "Excessive Exclamation Marks",
            "detail": f"{text.count('!')} exclamation marks - unusual for a legitimate business email."
        })

    caps = re.findall(r'\b[A-Z]{4,}\b', text)
    if len(caps) >= 3:
        score += 1
        flags.append({
            "category": "Excessive Capital Letters",
            "detail": f"ALL CAPS words ({', '.join(set(caps[:4]))}) are used to create panic."
        })

    return score, flags, urls


def analyze_email(text: str, sender: str = "") -> dict:
    model = _load_email_model()
    rule_score, flags, urls_found = _rule_score(text, sender)

    is_advance_fee  = any("Advance Fee" in f.get("category", "") for f in flags)
    has_hidden_link = any(f.get("category", "") in (
        "Possible Hidden Hyperlink", "Hidden URL Mismatch", "Suspicious Link Behind Text"
    ) for f in flags)

    if model != "fallback":
        cleaned   = re.sub(r'\s+', ' ', text.lower()).strip()
        prob      = float(model.predict_proba([cleaned])[0][1])
        rule_prob = min(rule_score / 10.0, 1.0)

        if is_advance_fee or rule_score >= 7:
            prob = max(prob, rule_prob, 0.75)
        elif has_hidden_link:
            prob = max(prob, rule_prob, 0.45)
        else:
            prob = 0.70 * prob + 0.30 * rule_prob

        model_used = "TF-IDF + Logistic Regression"
    else:
        prob = min(rule_score / 8.0, 0.99)
        model_used = "Rule-based fallback (run src/train_email.py)"

    lang = detect_language(text)

    if prob >= 0.65:
        risk_level = "high"
    elif prob >= 0.35:
        risk_level = "medium"
    else:
        risk_level = "low"

    risk_label = get_risk_label(risk_level, lang)
    fallback   = get_explanation("email", risk_level, lang)

    # Use first 500 chars of email as subject for the LLM prompt (enough context, not too long)
    subject_preview = text[:500].strip()

    from src.explainer import explain
    explanation, used_llm = explain("email", subject_preview, risk_level, prob * 100, flags, fallback)
    flags = [translate_flag(f, lang) for f in flags]

    return {
        "type":        "email",
        "language":    lang,
        "risk_level":  risk_level,
        "risk_label":  risk_label,
        "probability": round(prob * 100, 1),
        "explanation": explanation,
        "used_llm":    used_llm,
        "flags":       flags,
        "urls_found":  urls_found,
        "sender":      sender,
        "model_used":  model_used,
    }
