"""
phone_checker.py - Fraudulent phone number detection
Uses ML model when available, falls back to rules otherwise.
Explanations are generated by the LLM explainer when available.

Train first: python src/train_phone.py
"""

import re
import os
import sys
import warnings
import pandas as pd
import joblib

warnings.filterwarnings("ignore", category=UserWarning)
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from src.translations import detect_language, get_explanation, get_risk_label, translate_flag

PHONE_MODEL_PATH = os.path.join(os.path.dirname(__file__), "..", "models", "phone_model.pkl")
PHONE_FEATS_PATH = os.path.join(os.path.dirname(__file__), "..", "models", "phone_feature_cols.pkl")

_phone_model     = None
_phone_feat_cols = None


def _load_phone_model():
    global _phone_model, _phone_feat_cols
    if _phone_model is None:
        if os.path.exists(PHONE_MODEL_PATH):
            _phone_model     = joblib.load(PHONE_MODEL_PATH)
            _phone_feat_cols = joblib.load(PHONE_FEATS_PATH)
        else:
            _phone_model = "fallback"
    return _phone_model


PREMIUM_PREFIXES = {
    "be": ["090"],
    "nl": ["090", "091", "092", "093", "094", "095", "096", "097", "098"],
    "uk": ["09"],
    "de": ["0900", "0180"],
    "fr": ["089"],
    "us": ["900"],
}

SCAM_COUNTRY_CODES = [
    "1473", "1268", "1876", "1284", "1649", "1664", "1758", "1784",
    "1809", "1829", "1849",
    "255",   # Tanzania
    "234",   # Nigeria
    "90850", # Turkey premium
]


def _extract_features(number: str) -> dict:
    cleaned = re.sub(r'[\s\-\.\(\)\/]', '', str(number).strip())
    digits  = re.sub(r'\D', '', cleaned)

    is_premium = 0
    for _, prefixes in PREMIUM_PREFIXES.items():
        for pfx in prefixes:
            if digits.startswith(pfx) or (len(digits) > 2 and digits[2:].startswith(pfx)):
                is_premium = 1
                break

    stripped_digits = re.sub(r'\D', '', re.sub(r'^(\+|00)', '', cleaned))
    is_scam_cc = 0
    for cc in SCAM_COUNTRY_CODES:
        if stripped_digits.startswith(cc) or digits.startswith(cc):
            is_scam_cc = 1
            break

    num_digits = len(digits)
    return {
        "num_digits":          num_digits,
        "too_short":           int(num_digits < 7),
        "too_long":            int(num_digits > 15),
        "normal_len":          int(7 <= num_digits <= 15),
        "has_plus":            int(cleaned.startswith('+')),
        "starts_intl":         int(cleaned.startswith('+') or cleaned.startswith('00')),
        "is_premium":          is_premium,
        "is_scam_cc":          is_scam_cc,
        "repeating_digits":    int(bool(re.search(r'(\d)\1{4,}', digits))),
        "sequential_digits":   int(bool(re.search(r'012345|123456|234567|345678|456789|567890|678901', digits))),
        "all_same":            int(len(set(digits)) <= 2 and len(digits) > 5),
        "starts_0900":         int(digits.startswith('0900') or digits.startswith('900') or stripped_digits.startswith('900')),
        "starts_090":          int(digits.startswith('090') and not digits.startswith('0900')),
        "has_letters":         int(bool(re.search(r'[a-zA-Z]', cleaned))),
        "double_cc":           int(bool(re.search(r'^(\+00|\+\+|0000)', cleaned))),
        "is_nigerian_pattern": int(digits.startswith('234') or digits.startswith('00234')),
    }


def _rule_flags(number: str, features: dict) -> list:
    flags = []
    if features["is_premium"]:
        flags.append({
            "category": "Premium Rate Number",
            "detail": "Calling this number could cost several euros per minute. Legitimate organisations never ask you to call premium numbers."
        })
    if features["is_scam_cc"]:
        flags.append({
            "category": "Known Scam Country Code",
            "detail": "This country code is linked to callback scams or international fraud. Do not call back."
        })
    if features["repeating_digits"] or features["all_same"]:
        flags.append({
            "category": "Suspicious Number Pattern",
            "detail": "Repeating digits are a sign of a fake or spoofed number."
        })
    if features["starts_0900"] or features["starts_090"]:
        flags.append({
            "category": "Premium Prefix (090x)",
            "detail": "Numbers starting with 090 are premium rate in Belgium and the Netherlands."
        })
    if features["double_cc"]:
        flags.append({
            "category": "Possible Caller ID Spoofing",
            "detail": "Double country code prefix is a common caller ID spoofing technique."
        })
    if features["too_short"] or features["too_long"]:
        desc = "too short" if features["too_short"] else "too long"
        flags.append({
            "category": "Unusual Number Length",
            "detail": f"This number has {features['num_digits']} digits, which is {desc} for a standard phone number."
        })
    return flags


def _detect_country(number: str) -> str:
    c = re.sub(r'[\s\-\.\(\)\/]', '', number)
    if c.startswith("+32") or c.startswith("0032"): return "Belgium"
    if c.startswith("+31") or c.startswith("0031"): return "Netherlands"
    if c.startswith("+44"):                          return "United Kingdom"
    if c.startswith("+1"):                           return "USA/Canada"
    if c.startswith("+49"):                          return "Germany"
    if c.startswith("+33"):                          return "France"
    return "Unknown"


def check_phone(number: str) -> dict:
    model    = _load_phone_model()
    features = _extract_features(number)
    flags    = _rule_flags(number, features)

    if model != "fallback":
        X    = pd.DataFrame([features])[_phone_feat_cols]
        prob = float(model.predict_proba(X)[0][1])
        model_used = "Random Forest"
    else:
        score = (
            features["is_premium"]       * 3 +
            features["is_scam_cc"]       * 3 +
            features["starts_0900"]      * 2 +
            features["double_cc"]        * 2 +
            features["repeating_digits"] +
            features["too_short"] +
            features["too_long"]
        )
        prob = min(score / 8.0, 0.99)
        model_used = "Rule-based fallback (run src/train_phone.py)"

    lang = detect_language(number)

    if prob >= 0.65:
        risk_level = "high"
    elif prob >= 0.35:
        risk_level = "medium"
    else:
        risk_level = "low"

    risk_label = get_risk_label(risk_level, lang)
    fallback   = get_explanation("phone", risk_level, lang)

    from src.explainer import explain
    explanation, used_llm = explain("phone", number, risk_level, prob * 100, flags, fallback)
    flags = [translate_flag(f, lang) for f in flags]

    return {
        "type":        "phone",
        "language":    lang,
        "number":      number,
        "country":     _detect_country(number),
        "risk_level":  risk_level,
        "risk_label":  risk_label,
        "probability": round(prob * 100, 1),
        "explanation": explanation,
        "used_llm":    used_llm,
        "flags":       flags,
        "features":    features,
        "model_used":  model_used,
    }
