"""
predict.py - URL phishing prediction
Combines the ML model with typosquatting detection.
Explanations are generated by the LLM explainer when available.
"""

import os
import sys
import pandas as pd
import joblib

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from src.features import extract_features, FEATURE_COLS
from src.typosquatting import check_typosquatting
from src.translations import detect_language, get_explanation, get_risk_label, translate_flag

MODEL_PATH = os.path.join(os.path.dirname(__file__), "..", "models", "arcticsecurityshield.pkl")

_model = None


def _load_model():
    global _model
    if _model is None:
        if os.path.exists(MODEL_PATH):
            _model = joblib.load(MODEL_PATH)
        else:
            _model = "fallback"
    return _model


def _rule_based_score(features: dict) -> float:
    score = 0.1
    if features["has_suspicious_word"]: score += 0.30
    if features["has_ip"]:              score += 0.30
    if features["is_shortened"]:        score += 0.20
    if not features["has_https"]:       score += 0.15
    if features["num_at"] > 0:          score += 0.20
    if features["url_length"] > 100:    score += 0.10
    if features["subdomain_count"] > 2: score += 0.10
    return min(score, 0.99)


def predict(url: str) -> dict:
    features = extract_features(url)
    model = _load_model()

    if model != "fallback":
        X = pd.DataFrame([features])[FEATURE_COLS]
        prob = float(model.predict_proba(X)[0][1])
        model_used = "Random Forest"
    else:
        prob = _rule_based_score(features)
        model_used = "Rule-based fallback (no model found, run src/train.py)"

    typo = check_typosquatting(url)
    if typo["is_typosquat"] and prob < 0.75:
        prob = max(prob, 0.78)

    lang = detect_language(url)

    if prob >= 0.75:
        risk_level = "high"
    elif prob >= 0.45:
        risk_level = "medium"
    else:
        risk_level = "low"

    risk_label = get_risk_label(risk_level, lang)
    fallback   = get_explanation("url", risk_level, lang)

    flags = []
    if typo["is_typosquat"]:
        flags.append(f"Typosquatting: looks like '{typo['matched_brand']}' (edit distance: {typo['distance']})")
    if features["has_suspicious_word"]: flags.append("Contains suspicious keywords (e.g. 'login', 'verify', 'bank')")
    if features["has_ip"]:              flags.append("Uses an IP address instead of a domain name")
    if features["is_shortened"]:        flags.append("URL shortener used - real destination is hidden")
    if not features["has_https"]:       flags.append("No HTTPS - connection is not encrypted")
    if features["num_at"] > 0:          flags.append("Contains '@' - often used to disguise the real URL")
    if features["url_length"] > 100:    flags.append("Unusually long URL")
    if features["subdomain_count"] > 2: flags.append("Many subdomains - common trick to look like a trusted site")

    # Generate personalised explanation via LLM, fall back to hardcoded if unavailable
    from src.explainer import explain
    explanation, used_llm = explain("url", url, risk_level, prob * 100, flags, fallback)

    flags = [translate_flag(f, lang) for f in flags]

    return {
        "url":         url,
        "language":    lang,
        "probability": round(prob * 100, 1),
        "risk_level":  risk_level,
        "risk_label":  risk_label,
        "explanation": explanation,
        "used_llm":    used_llm,
        "flags":       flags,
        "features":    features,
        "typosquat":   typo,
        "model_used":  model_used,
    }
